Web/Controllers/OficinaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using Rotativa.AspNetCore;
using Microsoft.AspNetCore.Authorization;
//using JRBQTO.CORE.Models.Base;
using Microsoft.Extensions.Logging;
//using JRBQTO.CORE.ModelViews.Base;

namespace CasaCambio.Controllers
{
    public class OficinaController : Controller
    {
        //private readonly IUserHelper userHelper;
        private readonly IConfiguration _configuration;
        [Obsolete]
        private readonly IHostingEnvironment _env;
        ILogger<OficinaController> logger;
        
        private string _nameFolder = "../Oficina/";


        [Obsolete]
        public OficinaController(
                                 IConfiguration configuration,
                                 IHostingEnvironment env,
                                 ILogger<OficinaController> _logger)
        {
            _configuration      = configuration;
             _env               = env;
            logger              = _logger;
        }

    
        public string GetPathServer()
        {
            return $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}/";
        }

    
        [HttpGet]
        //[Route("fact/{company}")]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(JRBQTO.CORE.ModelViews.Base.LoginView credenciales)
        {
            return Redirect("~/Clientes/Index"); 
        }
    }
}

Web/Views/Oficina/Login.cshtml
@model JRBQTO.CORE.ModelViews.Base.LoginView
@{
    ViewData["Title"] = "Login";
    Layout = null;
}

<!DOCTYPE html>
<html class="h-100" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Casa Cambio - Prueba Tecnica</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="../../assets/images/favicon.png">
    <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous"> -->
    <link href="~/css/style.css" rel="stylesheet">

</head>

<body class="h-100">

    <div class="login-form-bg h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100">
                <div class="col-xl-6">
                    <div class="form-input-content">
                        <div class="card login-form mb-0">
                            <div class="card-body pt-5">
                                <a class="text-center" href="#"> <h4>Casa Cambio - Solo Click Ingresar</h4></a>

                                <form asp-controller="Oficina" asp-action="Login" method="post">
                                    <div class="form-group">
                                        <input type="email" asp-for="Email" class="form-control form-control-user" aria-describedby="emailHelp" placeholder="Correo" required>
                                    </div>
                                    <div class="form-group">
                                        <input asp-for="Password" type="password" class="form-control form-control-user" required>
                                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-block btn-flat">Entrada</button>
                                </form>
                                <p class="mt-5 login-form__footer">Dont have account? <a href="page-register.html" class="text-primary">Sign Up</a> now</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <!--**********************************
        Scripts
    ***********************************-->
    <script src="~/plugins/common/common.min.js"></script>
    <script src="~/js/custom.min.js"></script>
    <script src="~/js/settings.js"></script>
    <script src="~/js/gleek.js"></script>
    <script src="~/js/styleSwitcher.js"></script>
</body>
</html>