Web/Controllers/EmailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using CasaCambio.Core.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Logging;
using CasaCambio.Helper;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;

namespace CasaCambio.Controllers
{
    public class EmailsController : Controller
    {
        // GET: Categorias
        private readonly IConfiguration _configuration;
        [Obsolete]
        private readonly IHostingEnvironment _env;
        ILogger<EmailsController> logger;

        private string _nameFolder = "../Emails/";

        [Obsolete]
        public EmailsController(IConfiguration configuration,
                                 IHostingEnvironment env,
                                 ILogger<EmailsController> _logger)
        {
            _configuration = configuration;
            _env           = env;
            logger         = _logger;
        }

        [Obsolete]
        public async Task<ActionResult> Index()
        {
            CasaCambio.Web.ModelView.RootEmails rsEmails = new Web.ModelView.RootEmails();
            try
            {
                rsEmails = await ObtenerListaEmails();
            }
            catch (Exception ex) 
            {
                logger.LogError(ex.Message);
            }

            return View(rsEmails.result);

        }

        // GET: Categorias/Create
        public ActionResult Create()
        {
            return PartialView("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Create(Emails model)
        {
            var baseUrl = _configuration.GetValue<string>("baseUrlAPI");
            var recurso = "api/EmailsMaster/Create";

            var _api = new ManagerApi(baseUrl, recurso);
            string result = string.Empty;


            model.FechaReg = DateTime.Now;
            model.FechaAct = DateTime.Now;
            model.Estatus  = 1;

            var paramsJs = JsonConvert.SerializeObject(model);


            try
            {
                if (ModelState.IsValid)
                {
                    var Parameters = new Dictionary<string, string>
                            {
                                { "valueJson", paramsJs },
                            };

                    StringContent content = new StringContent(paramsJs, Encoding.UTF8, "application/json");
                    result                = await _api.ExecuteEndPointPostAsync(content);
                    var rsClienteNuevo    = JsonConvert.DeserializeObject<Web.ModelView.Root>(result);

                    //if (rsClienteNuevo.isSuccess) 
                    //{
                    //    CasaCambio.Web.ModelView.Root rsEmails = new Web.ModelView.Root();
                    //    rsEmails = await ObtenerListaClientes();
                    //    return PartialView("_TablaDetalles", rsEmails.result);
                    //}

                    CasaCambio.Web.ModelView.RootEmails rsEmails = new Web.ModelView.RootEmails();
                    rsEmails = await ObtenerListaEmails();
                    return PartialView("_TablaDetalles", rsEmails.result);

                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex.Message);
            }

            return PartialView("_TablaDetalles");
        }

        // GET: Categorias/Edit/5
        public async Task<ActionResult> Edit(int Id)
        {

            CasaCambio.Web.ModelView.RootSampleEmails rsEmails = new Web.ModelView.RootSampleEmails();

            try
            {
                rsEmails = await ObtenerEmail(Id);

                if (!rsEmails.isSuccess) 
                {
                    logger.LogError(rsEmails.message);
                    return PartialView("Edit");

                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex.Message);
                return PartialView("Edit");
            }

            return PartialView("Edit", rsEmails.result);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(Emails model)
        {
            var cliente = ObtenerEmail(model.IdCliente).Result.result;

            var baseUrl = _configuration.GetValue<string>("baseUrlAPI");
            var recurso = "api/EmailsMaster/Update";

            var _api = new ManagerApi(baseUrl, recurso);
            string result = string.Empty;

            //cliente.nombres   = model.Nombres;
            //cliente.apellidos = model.Apellidos;
            cliente.fechaAct  = DateTime.Now;

            var paramsJs = JsonConvert.SerializeObject(cliente);

            try
            {
                if (ModelState.IsValid)
                {
                    var Parameters = new Dictionary<string, string>
                            {
                                { "valueJson", paramsJs },
                            };

                    StringContent content = new StringContent(paramsJs, Encoding.UTF8, "application/json");
                    result       = await _api.ExecuteEndPointPostAsync(content);
                    var Result   = JsonConvert.DeserializeObject<CasaCambio.Web.ModelView.RootSample>(result);

                    if (!Result.isSuccess)
                    {
                        logger.LogError(Result.message);
                        return PartialView("_TablaDetalles");
                    }

                    CasaCambio.Web.ModelView.RootEmails rsEmails = new Web.ModelView.RootEmails();
                    rsEmails = await ObtenerListaEmails();

                    return PartialView("_TablaDetalles", rsEmails.result);

                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex.Message);
            }

            return PartialView("_TablaDetalles");
        }



        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {
            var cliente = ObtenerEmail(id).Result.result;

            var baseUrl = _configuration.GetValue<string>("baseUrlAPI");
            var recurso = "api/EmailsMaster/Update";

            var _api = new ManagerApi(baseUrl, recurso);
            string result = string.Empty;

            cliente.estatus = 0;

            var paramsJs = JsonConvert.SerializeObject(cliente);

            try
            {
                if (ModelState.IsValid)
                {
                    var Parameters = new Dictionary<string, string>
                            {
                                { "valueJson", paramsJs },
                            };

                    StringContent content = new StringContent(paramsJs, Encoding.UTF8, "application/json");
                    result = await _api.ExecuteEndPointPostAsync(content);
                    var Result = JsonConvert.DeserializeObject<CasaCambio.Web.ModelView.RootSample>(result);

                    if (!Result.isSuccess)
                    {
                        logger.LogError(Result.message);
                        return PartialView("_TablaDetalles");
                    }

                    CasaCambio.Web.ModelView.RootEmails rsEmails = new Web.ModelView.RootEmails();
                    rsEmails = await ObtenerListaEmails();

                    return PartialView("_TablaDetalles", rsEmails.result);

                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex.Message);
            }

            return PartialView("_TablaDetalles");
        }

        private async Task<Web.ModelView.RootEmails> ObtenerListaEmails()
        {

            CasaCambio.Web.ModelView.RootEmails rsEmails = new Web.ModelView.RootEmails();

            try
            {
                var baseUrl = _configuration.GetValue<string>("baseUrlAPI");
                var recurso = "api/EmailsMaster/GetAll";

                var _api = new ManagerApi(baseUrl, recurso);
                string result = string.Empty;
                rsEmails = new Web.ModelView.RootEmails();

                var baseAddress = new Uri(baseUrl + recurso);
                result = await _api.ExecuteEndPointGetAsync(baseAddress);
                rsEmails = JsonConvert.DeserializeObject<CasaCambio.Web.ModelView.RootEmails>(result);

            }
            catch (Exception ex)
            {
                logger.LogError(ex.Message);
            }

            return rsEmails;
        }


        private async Task<Web.ModelView.RootSampleEmails> ObtenerEmail(int Id)
        {
            CasaCambio.Web.ModelView.RootSampleEmails rsEmails = new Web.ModelView.RootSampleEmails();

            try
            {
                var baseUrl = _configuration.GetValue<string>("baseUrlAPI");
                var recurso = String.Format("api/EmailsMaster/Get?id={0}", Id.ToString());

                var _api = new ManagerApi(baseUrl, recurso);
                string result = string.Empty;

                var baseAddress = new Uri(baseUrl + recurso);
                result = await _api.ExecuteEndPointGetAsync(baseAddress);
                rsEmails = JsonConvert.DeserializeObject<CasaCambio.Web.ModelView.RootSampleEmails>(result);

                if (!rsEmails.isSuccess)
                {
                    logger.LogError(rsEmails.message);

                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex.Message);
            }

            return rsEmails;
        }

    }
}

Web/Views/Shared/_Layout1Ebqto.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>eBqto.com - La Gran Tienda</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Your page description here" />
    <meta name="author" content="" />

    <!-- css -->
    <link href="https://fonts.googleapis.com/css?family=Handlee|Open+Sans:300,400,600,700,800" rel="stylesheet">
    <link href="~/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/bootstrap-responsive.css" rel="stylesheet" />
    <link href="~/css/flexslider.css" rel="stylesheet" />
    <link href="~/css/prettyPhoto.css" rel="stylesheet" />
    <link href="~/css/camera.css" rel="stylesheet" />
    <link href="~/css/jquery.bxslider.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/css/custom.css" rel="stylesheet" />

    <!-- Theme skin -->
    <link href="~/color/default.css" rel="stylesheet" />

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="ico/apple-touch-icon-144-precomposed.png" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="ico/apple-touch-icon-114-precomposed.png" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="ico/apple-touch-icon-72-precomposed.png" />
    <link rel="apple-touch-icon-precomposed" href="ico/apple-touch-icon-57-precomposed.png" />
    <link rel="shortcut icon" href="~/img/favicom.png" />

    <script src="~/js/site.js"></script>

    <!-- =======================================================
      Theme Name: Eterna
      Theme URL: https://bootstrapmade.com/eterna-free-multipurpose-bootstrap-template/
      Author: BootstrapMade.com
      Author URL: https://bootstrapmade.com
    ======================================================= -->
</head>

<body>

    <div id="wrapper">

        <!-- start header -->
        <header class="header">
            <div class="top">
                <div class="container">
                    <div class="row">
                        <div class="span6">
                            <p class="topcontact"><i class="icon-phone"></i> +62 088 999 123</p>
                        </div>
                        <div class="span6">

                            <ul class="social-network">
                                <li><a href="#" data-placement="bottom" title="Facebook"><i class="icon-facebook icon-white"></i></a></li>
                                <li><a href="#" data-placement="bottom" title="Twitter"><i class="icon-twitter icon-white"></i></a></li>
                                <li><a href="#" data-placement="bottom" title="Linkedin"><i class="icon-linkedin icon-white"></i></a></li>
                                <li><a href="#" data-placement="bottom" title="Pinterest"><i class="icon-pinterest  icon-white"></i></a></li>
                                <li><a href="#" data-placement="bottom" title="Google +"><i class="icon-google-plus icon-white"></i></a></li>
                                <li><a href="#" data-placement="bottom" title="Dribbble"><i class="icon-dribbble icon-white"></i></a></li>
                            </ul>

                        </div>
                    </div>
                </div>
            </div>
            <div class="container">

                <div class="row nomargin">
                    <div class="span3">
                        <div class="logo">
                            <a asp-action="Inicio" asp-controller="EbqtoMain"><img src="/img/ebqto.png" alt="" /></a>
                        </div>
                    </div>
                    <div class="span3">
                        <div class="widget">
                            <form method="post">
                                <div class="input-append">
                                    <input class="span4" id="appendedInputButton" type="text" placeholder="Busca aqui" style="font-size:12px; height: 30px;">
                                    <button class="btn btn-theme" type="submit" style="font-size: 12px; height: 40px; width: 80px;">Buscar</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="span6">
                        <div class="navbar navbar-static-top">
                            <div class="navigation">
                                <nav>
                                    <ul class="nav topnav">
                                        <li class="dropdown">
                                            <a href="/EbqtoMain/Inicio"><i class="icon-home"></i> Inicio <i class="icon-angle-down"></i></a>
                                            <ul class="dropdown-menu">
                                                <li><a href="index-alt2.html">Mis Ordenes</a></li>
                                                <li><a href="index-alt3.html">Mis Favoritos</a></li>
                                                <li><a href="index-alt4.html">Ver Carrito</a></li>
                                                <li><a href="index-landingpage.html">Mi Historial</a></li>
                                            </ul>
                                        </li>

                                        <li class="dropdown">
                                            <a href="#">Categorias <i class="icon-angle-down"></i></a>
                                            <ul class="dropdown-menu">
                                                <li><a href="blog-left-sidebar.html">Supermercados</a></li>
                                                <li><a href="blog-right-sidebar.html">Ropa y Calzados</a></li>
                                                <li><a href="blog-fullwidth.html">Articulos del Hogar</a></li>
                                                <li><a href="post-left-sidebar.html">Lineas Blancas</a></li>
                                                <li><a href="post-right-sidebar.html">Repuestos Carros</a></li>
                                                <li><a href="post-right-sidebar.html">Repuestos Motos</a></li>
                                                <li><a href="post-right-sidebar.html">Repuestos Bicicletas</a></li>
                                                <li><a href="post-right-sidebar.html">Tecnologia y Computación</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                            <!-- end navigation -->
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- end header -->

        <div class="container">
            @RenderBody()
        </div>

        <footer>
            <div class="container">
                <div class="row">
                    <div class="span4">
                        <div class="widget">
                            <h5 class="widgetheading">Información</h5>
                            <ul class="link-list">
                                <li><a target="_blank" href="http://jrsoftware-001-site2.htempurl.com/about.html">Nuestra empresa</a></li>
                                <li><a target="_blank" href="http://jrsoftware-001-site2.htempurl.com/termycond.html">Terminos y Condiciones</a></li>
                                <li><a target="_blank" href="http://jrsoftware-001-site2.htempurl.com/polypriva.html">Politica de privacidad</a></li>
                                <li><a href="#">Desarrollo en curso</a></li>
                                <li><a href="#">Que hacemos ?</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="span4">
                        <div class="widget">
                            <h5 class="widgetheading">Dirección Contacto</h5>
                            <address>
                                <strong>JR-SOFTWARE</strong><br>
                                Calle 28 / 19 Centro<br>
                                Barquisimeto - Edo Lara<br />
                                Venezuela
                            </address>
                            <p>
                                <i class="icon-phone"></i> (0251) 266-7465 - (0416) 815-3975 <br>
                                <i class="icon-envelope-alt"></i> soporte@jrsoftware.com
                            </p>
                        </div>
                    </div>
                    <div class="span4">
                        <div class="widget">
                            <h5 class="widgetheading">Suscribete para promociones</h5>
                            <p>
                                Envianos a tu bandeja todas las promociones economicas para tu alcance
                            </p>
                            <form class="subscribe">
                                <div class="input-append">
                                    <input class="span2" id="appendedInputButton" type="text">
                                    <button class="btn btn-theme" type="button" onclick="alert('Modulo en Construcción')" >Suscribite</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div id="sub-footer">
                <div class="container">
                    <div class="row">
                        <div class="span6">
                            <div class="copyright">
                                <p><span>&copy; JR-SOFTWARE. Todos los derechos reservados</span></p>
                            </div>

                        </div>

                        <div class="span6">
                            <div class="credits">
                                <!--
                                  All the links in the footer should remain intact.
                                  You can delete the links only if you purchased the pro version.
                                  Licensing information: https://bootstrapmade.com/license/
                                  Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Eterna
                                -->
                                Diseñado por <a href="https://jr-soft.com/">JR-SOFTWARE</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <a href="#" class="scrollup"><i class="icon-angle-up icon-square icon-bglight icon-2x active"></i></a>

    <!-- javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="~/js/tableToJSON.js"></script>
    <script src="~/js/jquery.js" type="text/javascript"></script>
    <script src="~/js/jquery.easing.1.3.js" type="text/javascript"></script>
    <script src="~/js/bootstrap.js" type="text/javascript"></script>

    <script src="~/js/modernizr.custom.js" type="text/javascript"></script>
    <script src="~/js/toucheffects.js" type="text/javascript"></script>
    <script src="~/js/google-code-prettify/prettify.js" type="text/javascript"></script>
    <script src="~/js/jquery.bxslider.min.js" type="text/javascript"></script>
    <script src="~/js/camera/camera.js" type="text/javascript"></script>
    <script src="~/js/camera/setting.js" type="text/javascript"></script>

    <script src="~/js/jquery.prettyPhoto.js" type="text/javascript"></script>
    <script src="~/js/portfolio/jquery.quicksand.js" type="text/javascript"></script>
    <script src="~/js/portfolio/setting.js" type="text/javascript"></script>

    <script src="~/js/jquery.flexslider.js" type="text/javascript"></script>
    <script src="~/js/animate.js" type="text/javascript"></script>
    <script src="~/js/inview.js" type="text/javascript"></script>

    <!-- Contact Form JavaScript File -->
    <script src="~/contactform/contactform.js"></script>

    <!-- Template Custom JavaScript File -->
    <script src="~/js/custom.js"></script>

</body>

</html>

Web/Views/Shared/_LayoutBlank.cshtml
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Invoice500 | Base</title>
    <link rel="shortcut icon" href="~/Fact/dist/img/inv.jpeg">
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="~/Fact/bower_components/bootstrap/dist/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Fact/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Fact/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Fact/dist/css/AdminLTE.min.css">

    <link rel="stylesheet" href="~/Fact/dist/css/skins/_all-skins.min.css">

    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect. -->
    <link rel="stylesheet" href="~/Fact/dist/css/skins/skin-blue.min.css">
    <link href="https://cdn.datatables.net/select/1.3.0/css/select.bootstrap4.min.css" rel="stylesheet">

    <link rel="stylesheet" href="~/Fact/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <!-- jQuery 3 -->
    <script src="~/Fact/bower_components/jquery/dist/jquery.min.js"></script>

</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body>
    
    @RenderBody()

    <footer class="main-footer" style="text-align: center; padding-right: 30%">
        <!-- To the right -->
               
        <!-- Default to the left -->
        <strong>Copyright &copy; 2021 <a href="https://www.jrsoft.com">jr-brqto.com</a>.</strong> All rights reserved.
    </footer>


    <script src="~/Fact/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Fact/dist/js/adminlte.min.js"></script>


</body>
</html >

Web/Views/Shared/_LayoutFact.cshtml
@{

    

}

<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>JR - </title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon.png">
    <!-- Pignose Calender -->
    <link href="~/plugins/pg-calendar/css/pignose.calendar.min.css" rel="stylesheet">
    <!-- Chartist -->
    <link rel="stylesheet" href="~/plugins/chartist/css/chartist.min.css">
    <link rel="stylesheet" href="~/plugins/chartist-plugin-tooltips/css/chartist-plugin-tooltip.css">
    <!-- Custom Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/ventas.css" rel="stylesheet">
    <link href="~/css/adminlte.min.css" rel="stylesheet">
    <link href="~/plugins/select2/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.21/r-2.2.4/datatables.min.css" />

    <script src="~/plugins/jquery/jquery.min.js"></script>

</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition skin-blue sidebar-mini">

    @RenderBody()

</body>
</html>

<script src="/plugins/common/common.min.js"></script>
    <script src="/js/custom.min.js"></script>
    <script src="/js/settings.js"></script>
    <script src="/js/gleek.js"></script>
    <script src="/js/styleSwitcher.js"></script>
    
    <script src="/plugins/select2/js/select2.full.min.js"></script>

    <!-- Chartjs -->
    <script src="/plugins/chart.js/Chart.bundle.min.js"></script>
    <!-- Circle progress -->
    <script src="/plugins/circle-progress/circle-progress.min.js"></script>
    <!-- Datamap -->
    <!-- Morrisjs -->
    <script src="/plugins/raphael/raphael.min.js"></script>
    <script src="/plugins/morris/morris.min.js"></script>
    <!-- Pignose Calender -->
    <script src="/plugins/chartist/js/chartist.min.js"></script>
    <script src="/plugins/chartist-plugin-tooltips/js/chartist-plugin-tooltip.min.js"></script>
    <script src="/js/dashboard/dashboard-1.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.21/r-2.2.4/datatables.min.js"></script>
    <script src="/plugins/datatables/dataTables.select.min.js"></script>
    <script src="/js/alertgrowl.js"></script>
    <script src="/js/tableToJSON.js"></script>

    <script type="text/javascript">
    
        $(function () {
            $('.select2').select2()
        });

    </script>

Web/Views/Shared/_LoginPartialEbqto.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<ul class="navbar-nav">
@if (SignInManager.IsSignedIn(User))
{
    <li class="nav-item">
        <a  class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity.Name!</a>
    </li>
    <li class="nav-item">
        <form  class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
            <button  type="submit" class="nav-link btn btn-link text-dark">Logout</button>
        </form>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
    </li>
}
</ul>

Web/Views/Shared/_sideBarMenu.cshtml
@{
    
}

   <!--**********************************
        Sidebar start
    ***********************************-->
    <div class="nk-sidebar">
        <div class="nk-nav-scroll">
            <ul class="metismenu" id="menu">
                @* <li class="nav-label">Dashboard</li> *@

                <li class="mega-menu mega-menu-sm">
                    <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                        <i class="fa fa-product-hunt"></i><span class="nav-text">OPCIONES</span>
                    </a>
                    <ul aria-expanded="false">

                      <li><a asp-action="Index" asp-controller="Clientes">
                                <i class="fa fa-barcode pull-left"></i>
                                <p>Clientes</p>
                            </a></li>
                
                            <li><a asp-action="Index" asp-controller="Emails">
                                <i class="fa fa-list pull-left"></i>
                                <p>Emails</p>
                            </a></li>
                    </ul>
                </li>
            
            </ul>
        </div>
    </div>