Web/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using CasaCambio.Core.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Logging;
using CasaCambio.Helper;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;

namespace CasaCambio.Controllers
{
    public class ClientesController : Controller
    {
        // GET: Categorias
        private readonly IConfiguration _configuration;
        [Obsolete]
        private readonly IHostingEnvironment _env;
        ILogger<ClientesController> logger;

        private string _nameFolder = "../Oficina/";

        [Obsolete]
        public ClientesController(IConfiguration configuration,
                                 IHostingEnvironment env,
                                 ILogger<ClientesController> _logger)
        {
            _configuration = configuration;
            _env           = env;
            logger         = _logger;
        }

        [Obsolete]
        public async Task<ActionResult> Index()
        {
            CasaCambio.Web.ModelView.Root rsCLientes = new Web.ModelView.Root();
            try
            {
                rsCLientes = await ObtenerListaClientes();
            }
            catch (Exception ex) 
            {
                logger.LogError(ex.Message);
            }

            return View(rsCLientes.result);

        }

        [Obsolete]
        public async Task<ActionResult> ListEmailsPorCliente(int id)
        {
            CasaCambio.Web.ModelView.RootEmails rsCLientes = new Web.ModelView.RootEmails();
            try
            {
                var baseUrl = _configuration.GetValue<string>("baseUrlAPI");
                var recurso = string.Format("api/EmailsMaster/GetAllEmailByClients?Id={0}", id.ToString() );

                var _api      = new ManagerApi(baseUrl, recurso);
                string result = string.Empty;
                rsCLientes    = new Web.ModelView.RootEmails();

                var baseAddress = new Uri(baseUrl + recurso);
                result          = await _api.ExecuteEndPointGetAsync(baseAddress);
                rsCLientes      = JsonConvert.DeserializeObject<CasaCambio.Web.ModelView.RootEmails>(result);
            }
            catch (Exception ex)
            {
                logger.LogError(ex.Message);
            }

            return PartialView("../Emails/_TablaDetallesEmails", rsCLientes.result);

        }

        // GET: Categorias/Create
        public ActionResult Create()
        {
            return PartialView("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Create(Clientes model)
        {
            var baseUrl = _configuration.GetValue<string>("baseUrlAPI");
            var recurso = "api/ClientesMaster/Create";

            var _api = new ManagerApi(baseUrl, recurso);
            string result = string.Empty;


            model.FechaReg = DateTime.Now;
            model.FechaAct = DateTime.Now;
            model.Estatus  = 1;

            var paramsJs = JsonConvert.SerializeObject(model);


            try
            {
                if (ModelState.IsValid)
                {
                    var Parameters = new Dictionary<string, string>
                            {
                                { "valueJson", paramsJs },
                            };

                    StringContent content = new StringContent(paramsJs, Encoding.UTF8, "application/json");
                    result                = await _api.ExecuteEndPointPostAsync(content);
                    var rsClienteNuevo    = JsonConvert.DeserializeObject<CasaCambio.Web.ModelView.Root>(result);

                    //if (rsClienteNuevo.isSuccess) 
                    //{
                    //    CasaCambio.Web.ModelView.Root rsCLientes = new Web.ModelView.Root();
                    //    rsCLientes = await ObtenerListaClientes();
                    //    return PartialView("_TablaDetalles", rsCLientes.result);
                    //}

                    CasaCambio.Web.ModelView.Root rsCLientes = new Web.ModelView.Root();
                    rsCLientes = await ObtenerListaClientes();
                    return PartialView("_TablaDetalles", rsCLientes.result);

                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex.Message);
            }

            return PartialView("_TablaDetalles");
        }

        // GET: Categorias/Edit/5
        public async Task<ActionResult> Edit(int Id)
        {

            CasaCambio.Web.ModelView.RootSample rsCLientes = new Web.ModelView.RootSample();

            try
            {
                rsCLientes = await ObtenerCliente(Id);

                if (!rsCLientes.isSuccess) 
                {
                    logger.LogError(rsCLientes.message);
                    return PartialView("Edit");

                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex.Message);
                return PartialView("Edit");
            }

            return PartialView("Edit", rsCLientes.result);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(Clientes model)
        {
            var cliente = ObtenerCliente(model.IdCliente).Result.result;

            var baseUrl = _configuration.GetValue<string>("baseUrlAPI");
            var recurso = "api/ClientesMaster/Update";

            var _api = new ManagerApi(baseUrl, recurso);
            string result = string.Empty;

            cliente.nombres   = model.Nombres;
            cliente.apellidos = model.Apellidos;
            cliente.fechaAct  = DateTime.Now;

            var paramsJs = JsonConvert.SerializeObject(cliente);

            try
            {
                if (ModelState.IsValid)
                {
                    var Parameters = new Dictionary<string, string>
                            {
                                { "valueJson", paramsJs },
                            };

                    StringContent content = new StringContent(paramsJs, Encoding.UTF8, "application/json");
                    result       = await _api.ExecuteEndPointPostAsync(content);
                    var Result   = JsonConvert.DeserializeObject<CasaCambio.Web.ModelView.RootSample>(result);

                    if (!Result.isSuccess)
                    {
                        logger.LogError(Result.message);
                        return PartialView("_TablaDetalles");
                    }

                    CasaCambio.Web.ModelView.Root rsCLientes = new Web.ModelView.Root();
                    rsCLientes = await ObtenerListaClientes();

                    return PartialView("_TablaDetalles", rsCLientes.result);

                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex.Message);
            }

            return PartialView("_TablaDetalles");
        }



        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {
            var cliente = ObtenerCliente(id).Result.result;

            var baseUrl = _configuration.GetValue<string>("baseUrlAPI");
            var recurso = "api/ClientesMaster/Update";

            var _api = new ManagerApi(baseUrl, recurso);
            string result = string.Empty;

            cliente.estatus = 0;

            var paramsJs = JsonConvert.SerializeObject(cliente);

            try
            {
                if (ModelState.IsValid)
                {
                    var Parameters = new Dictionary<string, string>
                            {
                                { "valueJson", paramsJs },
                            };

                    StringContent content = new StringContent(paramsJs, Encoding.UTF8, "application/json");
                    result = await _api.ExecuteEndPointPostAsync(content);
                    var Result = JsonConvert.DeserializeObject<CasaCambio.Web.ModelView.RootSample>(result);

                    if (!Result.isSuccess)
                    {
                        logger.LogError(Result.message);
                        return PartialView("_TablaDetalles");
                    }

                    CasaCambio.Web.ModelView.Root rsCLientes = new Web.ModelView.Root();
                    rsCLientes = await ObtenerListaClientes();

                    return PartialView("_TablaDetalles", rsCLientes.result);

                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex.Message);
            }

            return PartialView("_TablaDetalles");
        }

        private async Task<Web.ModelView.Root> ObtenerListaClientes()
        {

            CasaCambio.Web.ModelView.Root rsCLientes = new Web.ModelView.Root();

            try
            {
                var baseUrl = _configuration.GetValue<string>("baseUrlAPI");
                var recurso = "api/ClientesMaster/GetAll";

                var _api = new ManagerApi(baseUrl, recurso);
                string result = string.Empty;
                rsCLientes = new Web.ModelView.Root();

                var baseAddress = new Uri(baseUrl + recurso);
                result = await _api.ExecuteEndPointGetAsync(baseAddress);
                rsCLientes = JsonConvert.DeserializeObject<CasaCambio.Web.ModelView.Root>(result);

            }
            catch (Exception ex)
            {
                logger.LogError(ex.Message);
            }

            return rsCLientes;
        }


        private async Task<Web.ModelView.RootSample> ObtenerCliente(int Id)
        {
            CasaCambio.Web.ModelView.RootSample rsCLientes = new Web.ModelView.RootSample();

            try
            {
                var baseUrl = _configuration.GetValue<string>("baseUrlAPI");

Web/Views/Clientes/Create.cshtml
@model CasaCambio.Core.Models.Clientes

@{
    Layout = null;

}

<div class="row">
    <div class="col-md-12">
        <form id="formagregar" asp-action="Create" asp-controller="Clientes">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" id="IdCliente" name="id_cliente" asp-for="IdCliente" value="0">

            <div class="row">
                <div class="col-md-2">
                    <label asp-for="DocumentoID" class="control-label">Documento ID</label>
                </div>
                <div class="col-md-10">
                    <input asp-for="DocumentoID" id="nombres" class="form-control" />
                    <span asp-validation-for="DocumentoID" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-2">
                    <label asp-for="Nombres" class="control-label">Nombres</label>
                </div>
                <div class="col-md-10">
                    <input asp-for="Nombres" id="Nombres" class="form-control" />
                    <span asp-validation-for="Nombres" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-2">
                    <label asp-for="Apellidos" class="control-label">Apellidos</label>
                </div>
                <div class="col-md-10">
                    <input asp-for="Apellidos" id="Apellidos" class="form-control" type="text" />
                    <span asp-validation-for="Apellidos" class="text-danger"></span>
                </div>
            </div>

        </form>
    </div>
</div>

Web/Views/Clientes/Edit.cshtml
@model CasaCambio.Web.ModelView.ResultClientesView

@{
    Layout = null;

}

<div class="row">
    <div class="col-md-12">
        <form id="formagregar" asp-action="Edit" asp-controller="Clientes">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" id="IdCliente" name="IdCliente" asp-for="idCliente" value="@Model.idCliente">
            
            <div class="row">
                <div class="col-md-2">
                    <label asp-for="documentoID" class="control-label">Documento ID</label>
                </div>
                <div class="col-md-10">
                    <input asp-for="documentoID" id="nombres" class="form-control" />
                    <span asp-validation-for="documentoID" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-2">
                    <label asp-for="nombres" class="control-label">Nombres</label>
                </div>
                <div class="col-md-10">
                    <input asp-for="nombres" id="Nombres" name="Nombres" class="form-control" />
                    <span asp-validation-for="nombres" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-2">
                    <label asp-for="apellidos" class="control-label">Apellidos</label>
                </div>
                <div class="col-md-10">
                    <input asp-for="apellidos" id="Apellidos" name="Apellidos" class="form-control" type="text" />
                    <span asp-validation-for="apellidos" class="text-danger"></span>
                </div>
            </div>

        </form>
    </div>
</div>

Web/Views/Clientes/Index.cshtml
@model IEnumerable<CasaCambio.Web.ModelView.ResultClientesView>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<label style="font-size: 10px">Administracion -> registro de categorias</label>*@
<H3>Clientes</H3>

<input type="hidden" id="Id" name="Id" value="0">

<div class="col-sm-12 mb-6 mb-sm-3" align="right">
    <a class="btn btn-warning" onclick="Nuevo()">
        <i class="fas fa-plus">Nuevo</i>
    </a>
</div>


<div class="card shadow mb-4">

    <div class="card-body">
        <div id="zonatable" class="table-responsive">

            @await Html.PartialAsync("_TablaDetalles", Model)

        </div>
    </div>
</div>

<div class="col-sm-10 mb-6 mb-sm-3" align="left">
    <a asp-action="ExportExcelCategorias" asp-controller="Clientes" class="btn btn-success">
        <i class="fas fa-excel">Exportar Excel</i>
    </a>&nbsp;

</div>



<div class="modal fade" id="FormModalEmails" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Emails</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body" id="bodyFormEmails"></div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                <a id="btnConfirmar" href="#" class="btn btn-danger">Confirmar</a>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="FormModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Nuevo Registro</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body" id="bodyForm"></div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                <a id="btnConfirmar" href="#" class="btn btn-danger">Confirmar</a>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="AsqModalDelete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Eliminar</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Esta seguro de eliminar este registro ?</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                <a id="btnConfirmarDelete" class="btn btn-danger">Confirmar</a>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="~/js/clientes.js"></script>

Web/Views/Clientes/_TablaDetalles.cshtml
@model IEnumerable<CasaCambio.Web.ModelView.ResultClientesView>

@{
    Layout = null;
}

<table id="tbDetallesClientes" class=" datatable table table-bordered" width="100%" cellspacing="0">
    <thead>
        <tr>
            <th>
                Documento ID
            </th>
            <th>
                Nombres
            </th>
            <th>
                Apellidos
            </th>
            <th>
                Fecha Reg
            </th>

            <th>
                Fecha Act
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody id="tbody">

        @if (Model != null)
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.documentoID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.nombres)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.apellidos)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fechaReg)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fechaAct)
                    </td>
                    <td>
                        <a class="btn btn-default" data-toggle="tooltip" data-original-title="Emails" onclick="EmailsClientes(@item.idCliente)">
                            <i class="fa fa-address-book"></i>
                        </a>

                        <a class="btn btn-default" data-toggle="tooltip" data-original-title="Editar" onclick="Editar(@item.idCliente)">
                            <i class="fa fa-edit"></i>
                        </a>

                        <a id="@item.idCliente" onclick="Eliminar(@item.idCliente)">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
            }
        }


    </tbody>
</table>